### ISSUE TITLE
Model number for GP2Y0A710K0F

### ISSUE THREAD

**Issue by davgao** [guillaume-rico/SharpIR#2]
Trying to get distance readings from this model using the example in the library. 

https://www.adafruit.com/products/1568

The readings seem to be inverted. I think it is related to the model number. 
Tried 100550 as model number from datasheet the values stayed the same.

**Comment by tibm** [comment]
See the last pull request. I added the GP2Y0A710K0F sensor. Refer to it with "100500".

**Comment by michaelyasay** [comment]
Can you also add "GP2YA41SK0F" sensor to the Library?

**Comment by guillaume-rico** [comment]
Done ! Function is based on datasheet

**Comment by michaelyasay** [comment]
Thank you! works fine with the "GP2YA41SK0F" sensor.
