### ISSUE TITLE
Generating Equations

### ISSUE THREAD

**Issue by aro1976** [guillaume-rico/SharpIR#4]
Hi,

How did you find out the values of 27.728 and -1.2045 from the equation below?
distanceCM = 27.728 \* pow(map(ir_val[NB_SAMPLE / 2], 0, 1023, 0, 5000)/1000.0, -1.2045);

Thanks,
Alessandro

**Comment by guillaume-rico** [comment]
Hi,

  Using data write in README.md , I found 28.988 and -1.173... I don't know why I have writed 27.728 and -1.2045....

  To find coefficients : in MSExcel, enter values of tension in first col and distance in second col. Then selected them and creat an "Scatter graph". Right click on the curve and "Add trend curve". Then select "Polynomial" and click on "Display equation on graph".

Regards,
