### ISSUE TITLE
getting raw values instead of CMs?

### ISSUE THREAD

**Issue by cristianmtr** [guillaume-rico/SharpIR#5]
Hey!

Would it be possible to get the raw values themselves instead of CMs? What would I need to change in the code? 

Is it the `1000` in these lines?

```
          distanceCM = 60.374 * pow(map(ir_val[NB_SAMPLE / 2], 0, 1023, 0, 5000)/1000.0, -1.16);
```

**Comment by guillaume-rico** [comment]
To get the raw value : 
distanceCM = ir_val[NB_SAMPLE / 2];

Regards,
