### ISSUE TITLE
difference between calculation factor in .cpp file and read.me

### ISSUE THREAD

**Issue by niek70** [guillaume-rico/SharpIR#7]
In SharpIR.cpp, the calculation factor for the 1080 model = " distanceCM = 27.728 * pow(...."

In the READ.ME it is: "Distance = 29.988 X POW(Volt , -1.173)...."

for me I think the last one is correct, but what is the correct one ?

**Comment by guillaume-rico** [comment]
You are right. I have commit the new version.
Thank you.

**Comment by niek70** [comment]
You're welcome

and thank you for the good work with the library
________________________________
Van: guillaume-rico <notifications@github.com>
Verzonden: zondag 13 oktober 2019 16:05
Aan: guillaume-rico/SharpIR <SharpIR@noreply.github.com>
CC: niek70 <niek70@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [guillaume-rico/SharpIR] difference between calculation factor in .cpp file and read.me (#7)


Closed #7<https://github.com/guillaume-rico/SharpIR/issues/7>.
